export const GET_REPORT_DATA_REQUEST = "GET_REPORT_DATA_REQUEST";
export const GET_REPORT_DATA_SUCCESS = "GET_REPORT_DATA_SUCCESS";
export const GET_REPORT_DATA_FAILURE = "GET_REPORT_DATA_FAILURE";

export const GET_METRICS_REQUEST = "GET_METRICS_REQUEST";
export const GET_METRICS_SUCCESS = "GET_METRICS_SUCCESS";
export const GET_METRICS_FAILURE = "GET_METRICS_FAILURE";

export const ADD_REPORT_REQUEST = "ADD_REPORT_REQUEST";
export const ADD_REPORT_SUCCESS = "ADD_REPORT_SUCCESS";
export const ADD_REPORT_FAILURE = "ADD_REPORT_FAILURE";

export const GET_FORMS_REQUEST = "GET_FORMS_REQUEST";
export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_FORMS_FAILURE = "GET_FORMS_FAILURE";

export const GET_FORMS_QUESTIONS_REQUEST = "GET_FORMS_QUESTIONS_REQUEST";
export const GET_FORMS_QUESTIONS_SUCCESS = "GET_FORMS_QUESTIONS_SUCCESS";
export const GET_FORMS_QUESTIONS_FAILURE = "GET_FORMS_QUESTIONS_FAILURE";
